name: Python Test

on:
  push:
    branches: 
      - main
      - test
  pull_request:
    branches: [ main ]

jobs:
  python-script-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: python TestMain.py
      - name: Other user repo checkout
        uses: actions/checkout@v3
        with:
          repository: kelloggm/specimin
          path: specimin
      - name: Run build
        run: | 
          cd specimin
          ./gradlew build expectedTestOutputsMustCompile
